# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "Blog"
description: > # this means to ignore newlines until "email:"
   My First Blog

email: koter84@gmail.com
#blog logo
#logo: "/assets/images/logo.jpg"
# blog cover
#cover: "/assets/images/cover.jpg"
cover: "/assets/images/cover_small.jpg"

name: 'Dennis'
author: 'Dennis'
author_image: "/assets/images/author.jpg"

# number of posts per page
paginate: 5

url: "http://koter84.github.io" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
#  - icon:	twitter
#    url:	https://twitter.com/???
#    desc: Follow me on twitter
#    share_url: http://twitter.com/share
#    share_title: ?text=
#    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

#  - icon:	github
#    url:	https://github.com/koter84
#    desc:	Fork me on github
#    share_url:
#    share_title:
#    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
